print("Hello, and welcome to your financial calculator!\n")
income = input("What is your monthly income?: ")
rent = input("What is your monthly rent: ")
utilities = input("What is your monthly utilities: ")
grocries = input("What is your monthly groceries: ")
transportation =input("What is your monthly transportation costs: ")
print("Your monthly income is ${income:.2f}\n")
print("Your monthly expenses are ${expenses:.2f}\n")
print("Your monthly savings is ${savings:.2f}\n")
print("Your monthly spending money is ${spending:.2f}\n")
print("Your rent is {int(prent)}% of your monthly income\n")
print("Your utilities are {int(putilities)}% of your monthly income\n")
print("Your groceries are {int(pgrocieries)}% of your monthly income\n")
print("Your transportation is {int(ptransportation)}% of your monthly income\n")
print("Your savings are {int(psavings)}% of your monthly income\n")
print("Your expenses are {int(pexpenses)}% of your monthly income\n")